# Generated by Django 3.1.3 on 2021-01-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201218_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
