# Generated by Django 3.1.4 on 2021-01-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210102_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
