# Generated by Django 3.1.5 on 2021-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency',
            new_name='ccy_btc',
        ),
        migrations.AddField(
            model_name='currency',
            name='ccy_eur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='ccy_rur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='ccy_usd',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
