# Generated by Django 3.1.5 on 2021-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210225_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='ccy_btc',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='ccy_eur',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='ccy_rur',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='ccy_usd',
        ),
        migrations.AddField(
            model_name='currency',
            name='base_ccy',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='buy',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='ccy',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='sale',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
